name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Ganti dengan branch utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to cPanel
        run: |
          rsync -avz --exclude='.git' ./ ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }}:${{ secrets.CPANEL_DIR }}
          ssh ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }} 'bash /path/to/your/repo/deploy.sh'
